import { Poppins } from 'next/font/google'
import Navigation from './components/Navigation';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {  icons: {
  icon: 'data:,'
},

  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
})

// export const metadata = {
//   icons: {
//     icon: 'data:,'
//   }
// }



export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navigation/>
        {children}
      </body>
    </html>
  );
}
